const quotes = [
  "I told my computer I needed a break, and now it won’t stop sending vacation ads.",
  "I’m not lazy, I’m just on energy-saving mode.",
  "If life gives you lemons, add vodka.",
  "I used to think I was indecisive, but now I’m not so sure.",
  "My bed and I love each other, only the alarm clock keeps trying to break us up.",
  "Why don’t scientists trust atoms? Because they make up everything.",
  "I asked the gym instructor if he could teach me to do the splits. He replied, “How flexible are you?” I said, “I can’t make it on Tuesdays.”",
  "I’m on a seafood diet. I see food, and I eat it.",
  "Life is short—smile while you still have teeth.",
  "My favorite exercise is a cross between a lunge and a crunch... I call it lunch.",
  "Whoever invented autocorrect should burn in hello.",
  "People say nothing is impossible, but I do nothing every day.",
  "I’m not great at the advice. Can I interest you in a sarcastic comment?",
  "They say don’t try this at home… so I went to a friend’s house!",
  "My phone battery lasts longer than most relationships these days.",
  "I don’t make mistakes. I date them.",
  "If stress burned calories, I’d be a supermodel.",
  "I put my phone in airplane mode and threw it—still didn’t fly.",
  "When life shuts a door… open it again. That’s how doors work.",
  "I cleaned my house for two hours. Now I need a nap to recover.",
  "My brain has too many tabs open.",
  "I’m the human version of a typo.",
  "I got 99 problems, but a WiFi connection ain't one.",
  "I meant to behave, but there were too many other options.",
  "I'm on a roll today. Butter me up.",
  "Mondays should be optional.",
  "Why is Peter Pan always flying? He neverlands.",
  "I tried to be normal once. Worst two minutes of my life.",
  "A balanced diet means a cupcake in each hand.",
  "I asked my mirror for motivation. It cracked.",
  "Procrastinators unite… tomorrow!",
  "A day without laughter is a day wasted.",
  "Why don’t skeletons fight each other? They don’t have the guts.",
  "I told my therapist about my fear of commitment… we’re meeting again next year.",
  "I'm not clumsy, the floor just hates me.",
  "If Monday had a face, I’d punch it.",
  "I love my six-pack so much, I protect it with a layer of fat.",
  "I follow a balanced diet: burger in one hand, fries in the other.",
  "The road to success is always under construction.",
  "They say money can’t buy happiness, but it can buy pizza. Same thing.",
  "My to-do list is just a list of things I’ve been avoiding.",
  "I don’t need a hair stylist, my pillow gives me a new hairstyle every morning.",
  "I’m just a cupcake looking for a stud muffin.",
  "The early bird might get the worm, but the second mouse gets the cheese.",
  "I dream of a better tomorrow, where chickens can cross the road without their motives being questioned.",
  "I don’t rise and shine—I caffeinate and hope.",
  "Exercise? I thought you said extra fries!",
  "Whoever said nothing is impossible never tried slamming a revolving door.",
  "My house was clean yesterday. Sorry you missed it.",
  "I enjoy long romantic walks to the fridge.",
  "If you can't convince them, confuse them.",
  "Don't watch the clock; do what it does. Keep going.",
  "The harder you work for something, the greater you'll feel when you achieve it.",
  "Success doesn’t come to you. You go to it.",
  "Push yourself, because no one else is going to do it for you.",
  "Believe in yourself and all that you are.",
  "Every day is a second chance.",
  "You don’t have to be great to start, but you have to start to be great.",
  "Great things never come from comfort zones.",
  "If it doesn’t challenge you, it won’t change you.",
  "Your only limit is you.",
  "Work hard in silence. Let success make the noise.",
  "Do something today that your future self will thank you for.",
  "Dreams don’t work unless you do.",
  "Don’t wait for opportunity. Create it.",
  "Stay positive, work hard, and make it happen.",
  "Action is the foundational key to all success.",
  "Don’t be afraid to fail. Be afraid not to try.",
  "Be stronger than your excuses.",
  "You are capable of amazing things.",
  "Start where you are. Use what you have. Do what you can.",
  "The key to success is to focus on goals, not obstacles.",
  "Your attitude determines your direction.",
  "Success is not for the lazy.",
  "The best view comes after the hardest climb.",
  "Everything you can imagine is real.",
  "You didn’t come this far to only come this far.",
  "Keep going. Everything you need will come to you.",
  "One day or day one—you decide.",
  "Doubt kills more dreams than failure ever will.",
  "Be a warrior, not a worrier.",
  "Hustle until you no longer need to introduce yourself.",
  "Winners never quit, and quitters never win.",
  "When you feel like quitting, think about why you started.",
  "Never stop learning, because life never stops teaching.",
  "Don’t let yesterday take up too much of today.",
  "The comeback is always stronger than the setback.",
  "Tough times never last, but tough people do.",
  "Success is what happens after you survive all your mistakes.",
  "A little progress each day adds up to big results.",
  "The best way to get started is to quit talking and begin doing.",
  "Life begins at the end of your comfort zone.",
  "Stay focused and never give up.",
  "Discipline is the bridge between goals and accomplishment.",
  "Make each day your masterpiece.",
  "Motivation gets you going, but discipline keeps you growing.",
  "Don’t be pushed around by the fears in your mind.",
  "Let your dreams be bigger than your fears.",
  "Consistency is what transforms average into excellence.",
  "You are your only competition.",
  "Set goals. Stay quiet about them. Smash them. Clap for your damn self.",
  "Don’t just exist, live.",
  "Be the energy you want to attract.",
  "Nothing worth having comes easy.",
  "It’s going to be hard, but hard is not impossible.",
  "No pressure, no diamonds.",
  "You don’t grow when you’re comfortable.",
  "Never give up on a dream just because of the time it will take.",
  "Stay hungry, stay foolish.",
  "Winners focus on winning, losers focus on winners.",
  "Fall seven times, stand up eight.",
  "Don't stop when you're tired. Stop when you're done.",
  "Dream big, start small, act now.",
  "Do what you can with what you have, where you are.",
  "It always seems impossible until it’s done.",
  "Act as if what you do makes a difference. It does.",
  "Be fearless in the pursuit of what sets your soul on fire.",
  "You don’t find willpower, you create it.",
  "One small positive thought in the morning can change your whole day.",
  "You are enough.",
  "Don’t limit your challenges, challenge your limits.",
  "Turn “I wish” into “I will.”",
  "Live more, worry less.",
  "Prove them wrong.",
  "Focus on the step in front of you, not the whole staircase.",
  "Nothing changes if nothing changes.",
  "Your mind is a powerful thing.",
  "Stay humble, work hard, be kind.",
  "You are braver than you believe.",
  "You only fail when you stop trying.",
  "Don't fear failure—fear being in the exact same place next year.",
  "The best investment you can make is in yourself.",
  "Show up even when no one else does.",
  "Be proud of how far you’ve come.",
  "You’re one decision away from a totally different life.",
  "Create the life you can’t wait to wake up to.",
  "Don’t settle.",
  "Good things take time.",
  "Stop doubting yourself.",
  "Think it. Want it. Get it.",
  "Let your hustle be louder than your mouth.",
  "If not now, when?",
  "Some people dream of success, others wake up and work for it.",
  "Don’t quit. Suffer now and live the rest of your life as a champion.",
  "Believe in your infinite potential.",
  "Make it happen. Shock everyone.",
  "Don’t stop until you’re proud.",
  "You’ve got this.",
  "Progress, not perfection.",
  "Turn your wounds into wisdom.",
  "The only way to do great work is to love what you do.",
  "Programming isn't just code, it's a love story between you and the machine.",
  "Talk is cheap. Show me the code.",
  "First, solve the problem. Then, write the code.",
  "Code is like humor. When you have to explain it, it’s bad.",
  "Simplicity is the soul of efficiency.",
  "Experience is the name everyone gives to their bugs.",
  "Java is to JavaScript what car is to Carpet.",
  "Clean code always looks like it was written by someone who cares.",
  "Any fool can write code that a computer can understand. Good programmers write code that humans can understand.",
  "The best error message is the one that never shows up.",
  "Programming is the art of algorithm design and the craft of debugging errant code.",
  "A good programmer is someone who looks both ways before crossing a one-way street.",
  "Coding is today's language of creativity.",
  "First law of programming: any change that you make will introduce at least one new bug.",
  "Programs must be written for people to read, and only incidentally for machines to execute.",
  "Always code as if the guy who ends up maintaining your code will be a violent psychopath who knows where you live.",
  "The best code is no code at all.",
  "If debugging is the process of removing software bugs, then programming must be the process of putting them in.",
  "One man’s crappy software is another man’s full-time job.",
  "Software is like sex: it's better when it's free.",
  "The function of good software is to make the complex appear simple.",
  "Good code is its own best documentation.",
  "The best performance improvement is the transition from the nonworking state to the working state.",
  "Computers are fast; programmers keep it slow.",
  "Debugging is twice as hard as writing the code in the first place.",
  "Don’t comment bad code—rewrite it.",
  "The cleaner your code is, the more bugs you can find.",
  "You should name a variable using the same care with which you name a first-born child.",
  "There is always one more bug to fix.",
  "Logic is the beginning of wisdom, not the end.",
  "Make it work, make it right, make it fast.",
  "Programming is breaking a big task into smaller ones and crying about each one.",
  "Keep calm and code on.",
  "Good programmers write good code. Great programmers reuse it.",
  "You miss 100% of the shots you don’t take — and 100% of the bugs you don’t test.",
  "A day without code is like... just kidding, I have no idea.",
  "Programming: Turning caffeine into software.",
  "Eat, Sleep, Code, Repeat.",
  "Behind every successful app is a programmer who didn’t give up.",
  "Code like a poet, test like a scientist.",
  "Coding is the closest thing we have to a superpower.",
  "Sometimes it’s not a bug, it’s a feature.",
  "The only constant in programming is change.",
  "Every great developer you know got there by solving problems they were unqualified to solve until they actually did it.",
  "A good bug report is worth its weight in code.",
  "Git happens.",
  "There’s no place like 127.0.0.1",
  "The code you write today will haunt you tomorrow.",
  "Real programmers count from 0.",
  "Code never lies, comments sometimes do.",
  "Hello World — the start of every journey.",
  "The best way to learn a language is to write bugs in it.",
  "Coding is not just about syntax, it’s about logic.",
  "You can't make everyone happy. You're not a code editor.",
  "There’s beauty in well-written code.",
  "Your code is your signature.",
  "Build things that scale, not just compile.",
  "Software developers have a unique talent of solving problems they create themselves.",
  "Behind every great app is a tired developer.",
  "Code hard or go home.",
  "Common sense is like deodorant. The people who need it most never use it.",
  "I told my wife she was drawing her eyebrows too high. She looked surprised.",
  "I used to play piano by ear, now I use my hands.",
  "I thought I wanted a career; turns out I just wanted a paycheck.",
  "I have a joke on construction, but I’m still working on it.",
  "Parallel lines have so much in common… it’s a shame they’ll never meet.",
  "I changed my password to “incorrect,” so whenever I forget it, the computer says, “Your password is incorrect.”",
  "My wallet is like an onion—opening it makes me cry.",
  "A clean house is a sign of a broken computer.",
  "If at first you don’t succeed, skydiving definitely isn’t for you.",
  "I told my laptop we were done. It just gave me a blue screen of sadness.",
  "I bought a ceiling fan the other day. Complete waste of money. He just stands there applauding and saying “Ooh, I love how smooth it is!”",
  "I started out with nothing, and I still have most of it.",
  "I talk to myself because I need expert advice.",
  "Don’t worry if plan A doesn’t work out. There are 25 more letters in the alphabet.",
  "If you think nobody cares if you're alive, try missing a couple of payments.",
  "My boss said I should dress for the job I want, not the job I have. Now I’m sitting in a disciplinary meeting dressed as Batman.",
  "The best way to lie is to tell the truth… carefully edited truth.",
  "I used to think I was a people person… but people ruined that for me.",
  "I hate it when people use big words just to make themselves sound perspicacious.",
  "I asked Alexa to make me laugh. She showed me my bank account.",
  "Running late is my cardio.",
  "I’m not arguing, I’m just explaining why I’m right.",
  "My dog is my best therapist. He listens, cuddles, and never judges.",
  "When nothing goes right… go left.",
  "I childproofed my house but they still get in.",
  "Some people graduate with honors, I am just honored to graduate.",
  "I’m not short, I’m concentrated awesome.",
  "I love deadlines. I like the whooshing sound they make as they fly by.",
  "Don’t give up on your dreams—keep sleeping.",
  "I always arrive late at the office, but I make up for it by leaving early.",
  "To be old and wise, you must first be young and stupid.",
  "Laughter is the best medicine, unless you’re laughing for no reason… then you need medicine.",
  "Zombies eat brains. Don’t worry, you’re safe.",
  "I opened a bakery. I kneaded the dough.",
  "Math teacher called me average—how mean!",
  "I know they say money talks, but mine just waves goodbye.",
  "I accidentally wore a red shirt to Target and ended up helping people for two hours.",
  "Life’s too short to remove USB safely.",
  "Never trust code you didn’t write yourself.",
  "Keep your code DRY — Don’t Repeat Yourself.",
  "Semicolons can break hearts.",
  "Code like it’s your last day.",
  "Your logic should be stronger than your coffee.",
  "Think twice, code once.",
  "A well-written loop is poetry.",
  "Learn algorithms, not just frameworks.",
  "A real coder doesn’t fear the dark — we thrive in dark themes.",
  "Real debugging starts when you think it’s fixed.",
  "Don't code and drive.",
  "We don't make bugs, we create unexpected features.",
  "Compiling... fingers crossed.",
  "Code smart, not hard.",
  "Silence is golden, unless you have kids… then it’s suspicious.",
  "I'm great at multitasking. I can waste time, be unproductive, and procrastinate all at once.",
  "I’m so bright my mother calls me “sun.”",
  "Today’s forecast: 100% chance of requiring more coffee.",
  "I’m reading a book on anti-gravity. It’s impossible to put down.",
  "I'm not weird, I'm limited edition.",
  "Don’t take life too seriously—you’ll never get out of it alive.",
  "I'm not arguing, I'm just passionately expressing my opinion.",
  "I asked my phone for directions, and it told me to “get a life.”",
  "My resume is just a list of places I’ve used WiFi.",
  "Deadlines make great debuggers.",
  "Break problems before they break you.",
  "You are only one bug away from genius.",
  "Arrays start at 0. Respect that.",
  "Without code, it’s just a screen.",
  "IDEs are our second home.",
  "Syntax is temporary, logic is forever.",
  "What you code is who you are.",
  "Fixing bugs teaches more than writing features.",
  "Variables come and go, but logic remains.",
  "Even your code needs a break sometimes.",
  "Refactor like a boss.",
  "Real devs commit early and often.",
  "One does not simply deploy on Friday.",
  "Love is temporary, commits are forever.",
  "Life is too short to write bad code.",
  "Coding is therapy for logical minds.",
  "When life throws errors, throw exceptions.",
  "Your compiler is your best critic.",
  "Coding is an adventure in logic-land.",
  "The best coders are constant learners.",
  "Stack Overflow is my co-pilot.",
  "Every keystroke is a step toward success.",
  "Good logic beats fancy syntax.",
  "Code is art, not instructions.",
  "Write code, change the world.",
];

module.exports = quotes;
